Updated Docker-image base to phusion/baseimage:0.11
sharelatex/sharelatex-docker-image pull request #105
Opened 2019-07-22 10:04 UTC by mserranom

Fixes https://github.com/overleaf/issues/issues/2043

2019-07-23 08:42 UTC, JuneKelly requested changes
Looks good, one change

2019-07-23 08:42 UTC, ShaneKilkelly commented on Dockerfile-base
> -ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2017/bin/x86_64-linux/
I think we'll want to stay on texlive 2017 until we have a fully-tested upgrade in production.

(we still ship texlive 2017 in prod, and we intend to upgrade it in the next few months)

2019-07-23 09:29 UTC, JuneKelly approved these changes

2019-08-06 10:39 UTC, mserranom commented
On hold until Community/ServerPro images are revived and a decision over texlive version is final.

2019-08-07 08:53 UTC, mserranom commented
Closing in favour of https://github.com/overleaf/docker-image/pull/107

2019-08-07 08:53 UTC, closed without merging