Copy synctex executable to docker host
sharelatex/sharelatex-docker-image pull request #129
Opened 2019-11-07 17:04 UTC by mserranom

When using Sandbox Compiles, CLSI starts TexLive containers, and in that process `synctex` executable available in the host mounted in the container.(https://github.com/overleaf/clsi/blob/f285e08ee055e7b0fc0c81d598a61f40cfdebeb4/app/coffee/DockerRunner.coffee#L153)

This PR makes `synctex` available in the host by copying over the executable inside `sharelatex` container into to the mounted volume (https://github.com/overleaf/overleaf/blob/d09b6149e12a343ae9adf9dcbc8afdf6301dc9ee/docker-compose.yml#L21), so it can be subsequently mounted in the TexLive containers.

2019-11-07 17:32 UTC, das7pad commented
Bundling `synctex` into the docker image that is used for the compiles is another option.

2019-11-08 11:05 UTC, ShaneKilkelly commented
Hmm, there's something about this scenario that seems a bit odd. I worry that this binary juggling will be fragile in the long run. Plus, there's something strange about copying a binary out of one environment, into another, then into another again. (well, mounting in the last case, but the point stands).

Would it be enough to ask the users to install synctex on the host and then set the host-path? Or is synctex hard to install? 

cc @briangough

2019-11-08 11:10 UTC, mserranom commented
> Would it be enough to ask the users to install synctex
Definitely doable, it's a matter of friction vs oddity. I'd personally favour a frictionless approach (we can highlight in the docs that this executable is being copied over?)

2019-11-08 15:31 UTC, ShaneKilkelly commented
Also, just to put it in writing: we've discussed the possibility of just documenting a one-off command that the admin could run to copy the synctex binary out of the sharelatex container and onto the host.

2019-11-11 09:40 UTC, JuneKelly requested changes
Looking good in general, one suggestion to reduce duplication.

2019-11-11 09:40 UTC, ShaneKilkelly commented on runit/clsi-sharelatex/run
> +    mkdir -p /var/lib/sharelatex/bin
I think you could use `dirname $SYNCTEX` here, to avoid repeating the path.

2019-11-14 11:27 UTC, ShaneKilkelly commented
As discussed just now with @mserranom , one final suggestion: add an environment flag that the user can set if they don't want this behaviour, something like `DISABLE_SYNCTEX_BINARY_COPY`, or whatever makes sense.

2019-11-21 15:08 UTC, JuneKelly approved these changes
:tada:

2019-11-22 09:12 UTC, merged