Added environment variable for AWS SES region
sharelatex/sharelatex-docker-image pull request #136
Opened 2020-02-14 11:16 UTC by PierreBeucher

By default AWS SES will be used with `us-east-1` region and it requires a manual fix to use another region (see https://github.com/overleaf/web/issues/656)

This MR add the environment variable `SHARELATEX_EMAIL_AWS_SES_REGION` in settings to override the default setting when needed (and still use `us-east-1` by default)

2020-02-17 17:11 UTC, das7pad requested changes
Thank you for your contribution.

This is a good addition. Just a minor request before I can approve.

2020-02-17 17:11 UTC, das7pad commented on settings.coffee
> +      region: process.env["SHARELATEX_EMAIL_AWS_SES_REGION"] or 'us-east-1'
```suggestion
      region: process.env["SHARELATEX_EMAIL_AWS_SES_REGION"]
```

Please remove the fallback value and let the aws-sdk handle it.

```js
> const aws = require('aws-sdk')
undefined
> new aws.SES({}).config.region
undefined
> new aws.SES({region: process.env["THIS_DOES_NOT_EXIST"]}).config.region
undefined
> new aws.SES({region: 'us-east-1'}).config.region
'us-east-1'
```

2020-02-17 18:00 UTC, jdleesmiller commented
(And we'll need you to accept the CLA before we can merge, please: https://github.com/overleaf/overleaf/blob/master/CONTRIBUTING.md#contributor-license-agreement . )

2020-02-26 15:22 UTC, mserranom commented
We've migrated this repo to https://github.com/overleaf/overleaf. I proceed to close this PR, please  feel free to raise a new PR in the new location.

2020-02-26 15:22 UTC, closed without merging