Updating texlive path to current version
sharelatex/sharelatex-docker-image pull request #91
Opened 2018-05-04 21:02 UTC by magic-lantern

This minor path change fixes the issue #90 as reported by @flowgunso

2018-07-06 02:20 UTC, jubilee2 approved these changes
i think it is good for merge

2019-05-05 10:36 UTC, prohde requested changes
Maybe this should be updated to TeX Live version 2019 now?

2019-05-05 10:36 UTC, prohde commented on Dockerfile-base
> +ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2018/bin/x86_64-linux/
Maybe this should be updated to version 2019 now?

`ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2019/bin/x86_64-linux/`

2019-10-23 10:32 UTC, mserranom commented
Outdated.

2019-10-23 10:32 UTC, closed without merging